### ISSUE TITLE
Issue with installation

### ISSUE THREAD

**Issue by 411an13** [csoneson/compcodeR#18]
A colleague and I were unable to run "library(compcodeR)" in R (we both tried on our separate machines). Has this been encountered before?

## Running `library(compcodeR)` in the terminal:
```
> library(compcodeR)
Loading required package: sm
Package 'sm', version 2.2-5.7: type help(sm) for summary information
Error: package or namespace load failed for ‘compcodeR’:
 .onLoad failed in loadNamespace() for 'tcltk', details:
  call: file(path.expand(filename), "rb")
  error: cannot open the connection
In addition: Warning message:
In file(path.expand(filename), "rb") :
  cannot open file '/Users/aphillip/anaconda3/envs/analysis_env/lib/R/library/tcltk/libs//tcltk.so': No such file or directory
```
### In terminal:
```
mamba install -c conda-forge r-biocmanager
```
### Within R:
```
BiocManager::install("compcodeR")
```
### Error:
```
> BiocManager::install("compcodeR")
Bioconductor version 3.16 (BiocManager 1.30.21), R 4.2.3 (2023-03-15)
Installing package(s) 'BiocVersion'
trying URL 'https://bioconductor.org/packages/3.16/bioc/src/contrib/BiocVersion_3.16.0.tar.gz'
Content type 'application/gzip' length 965 bytes
==================================================
downloaded 965 bytes

* installing *source* package ‘BiocVersion’ ...
** using staged installation
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (BiocVersion)

The downloaded source packages are in
    ‘/private/var/folders/tl/d72ycs3s6fz_x99nddcb_lch0003c0/T/RtmptHOGUl/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Old packages: 'digest', 'edgeR', 'limma'
n
 Warning message:
package(s) not installed when version(s) same as or greater than current; use
  `force = TRUE` to re-install: 'compcodeR'
> library(compcodeR)
Loading required package: sm
Package 'sm', version 2.2-5.7: type help(sm) for summary information
Error: package or namespace load failed for ‘compcodeR’:
 .onLoad failed in loadNamespace() for 'tcltk', details:
  call: file(path.expand(filename), "rb")
  error: cannot open the connection
In addition: Warning message:
In file(path.expand(filename), "rb") :
  cannot open file '/Users/jespinoz/anaconda3/envs/r_env/lib/R/library/tcltk/libs//tcltk.so': No such file or directory
```

**Comment by jolespin** [comment]
Also getting this issue.  Is there any way to get around the `tcltk.so` library issue? I tried installing through a couple of different methods.  Also tried the developmental version but no luck.

**Comment by csoneson** [comment]
Hi both, thanks for reaching out. Could you try installing `compcodeR` from the `shinygui` branch and see if that works for you? In other words:

```
BiocManager::install("csoneson/compcodeR", ref = "shinygui")
```

This branch contains an experimental comparison GUI that is based on `shiny` rather than `tcltk`, and thus shouldn't need `tcltk`. The new GUI (`runComparisonShiny()`) is not yet well tested, but you can try it out, and if nothing else you should be able to run the comparison programmatically (via `runComparison()`).

**Comment by jolespin** [comment]
The main reason I wanted to use it was to generate compositional data for benchmarking but I found a hack around it.  I just copied the relevant scripts into a single R script and then wrapped the function w/ argparse.  Here's the executable in case anyone encounters something similar. 
[compcodeR_generateSyntheticData.zip](https://github.com/csoneson/compcodeR/files/11940110/compcodeR_generateSyntheticData.zip)

3 scripts in there: 
* compcodeR_generateSyntheticData.r - Has your package's code in a form where you can load functions w/ `source`. 
* test.r - Just tests the above code to make sure it works
* generate_compositional_data.r - Wraps up the code in argparse so you can just have a single executable to generate the counts data
